[package]
name = "bad-phf"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
phf_generator = { path = "../rust-phf-dbg/phf_generator" }
phf_shared = "0.11.2"
tinyrand = "0.5.0"
